### ISSUE TITLE
Thumbnail Graphics, Screen color options with brightness control

### ISSUE THREAD

**Issue by nonyabizwax** [bigtreetech/PandaTouch#56] opened 2024-03-29 17:57 UTC
(>) Would like to see the thumbnail of the print displayed on the screen if possible . (>) Would like to see options to manipulate the colors of the screen as well as to (>) dim or brighten the display if possible.

**Comment by bigtreetech** [comment] 2024-04-02 19:57
Duplicate of #12 #5 and others. Please reference the closed and open items for resolutions and future plans.

**Closed by bigtreetech** 2024-04-02 19:57 UTC
Labels: duplicate
