### ISSUE TITLE
Remove offensive Panda imagery 

### ISSUE THREAD

**Issue by heelsmj** [bigtreetech/PandaTouch#52] opened 2024-03-24 03:58 UTC
It is appalling in this day and age that you would portray a majestic animal such as a panda in this fashion. A panda represents inclusivity with its white and black fur. Don’t you know that they must be venerated? The tech sector is moving on from such negative portrayals of animals. Animals are people too! BTW Pandas are also stopping climate change since they eat bamboo and therefore fart less methane than most other animals. Save the panda! Please remove the offensive imagery in your next firmware update!

in place of the offensive panda you can have a 3D image of the model currently printing.

**Comment by looxonline** [comment] 2024-03-24 09:31
A(funny) duplicate of #14

**Closed by looxonline** 2024-03-24 09:31 UTC
