### ISSUE TITLE
Embarrassing Children's Cartoon Character

### ISSUE THREAD

**Issue by Jgelwix** [bigtreetech/PandaTouch#54] opened 2024-03-25 04:25 UTC
Is it possible to switch this childish panda cartoon image to something more respectable? I am embarrassed to have someone come by my shop and see it. Something professional would be excellent (or a PNG of the object being printed, if possible). 

Thank you.

**Comment by looxonline** [comment] 2024-03-25 06:52
Duplicate of #51 and also in the new firmware you'll be able to set the image yourself.

**Closed by looxonline** 2024-03-25 06:52 UTC
Labels: duplicate
