### ISSUE TITLE
Request - Ability to put something useful in place of the panda image

### ISSUE THREAD

**Issue by chrisrevv** [bigtreetech/PandaTouch#104] opened 2024-08-01 11:42 UTC
make the panda image dynamic, ability to display AMS status OR show fan speeds ect, a static image is a waste of real estate if we cant have the model preview showing.

**Comment by kurim** [comment] 2024-08-01 12:33
You mean things like this: https://github.com/bigtreetech/PandaTouch/issues/14 https://github.com/bigtreetech/PandaTouch/issues/53

**Comment by bigtreetech** [comment] 2024-08-01 13:10
Duplicate of existing items as already mentioned. We have plans for the real estate that currently seems like it can be better utilised. Thumbs should be coming in some form or another soon and the printer image will be occupied by a feature coming later this month.

**Closed by bigtreetech** 2024-08-01 13:10 UTC
